doc(xquery.xml): add in-built function map options
eXist-db/documentation pull request #672
Opened 2021-08-11 10:02 UTC by marmoure

see https://github.com/eXist-db/exist/pull/3990
currently only ```expand-xinlude``` is supported  more options docs to be added later.

2021-08-11 10:14 UTC, duncdrum approved these changes
Changes are good, and valid, the errors reported by cypress are unrelated since currently `:latest` is broken 

see https://github.com/eXist-db/dashboard/issues/199

2021-09-15 14:14 UTC, adamretter approved these changes
LGTM :-)
Thanks Younes.

2021-09-15 14:39 UTC, duncdrum requested changes

2021-09-15 14:39 UTC, duncdrum commented on src/main/xar-resources/data/xquery/xquery.xml
> +                    For eXist-db legacy serialization parameters The option's QName must be exist:serialize as show in the example above
please use `<literal>` around `exist:serialize`

2021-09-15 14:55 UTC, duncdrum approved these changes
thank you looking good

2021-09-15 22:27 UTC, merged